import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { isAbsolute, join, relative, sep } from 'node:path';
import { pathToFileURL } from 'node:url';
import { jobsDir, repoRoot } from './data-dir.ts';

/**
 * User jobs scaffold (J-2, plan §5.2/§5.5; grill R2-2): keeps the four
 * platform-owned artifacts inside `$DATA_DIR/jobs` in sync with the
 * repository. Every write is idempotent and content-guarded - bytes that
 * differ from the expected content are rewritten (self-healing), so a moved
 * repository or a stray manual edit can never leave the scaffold stale. The
 * only files the admin surface ever writes in this directory are user job
 * scripts; everything else here is generated.
 */

const SDK_MODULE_SEGMENTS = ['src', 'lib', 'server', 'jobs', 'jobs-sdk.ts'];
const FACADE_MODULE_SEGMENTS = ['src', 'lib', 'server', 'jobs', 'sdk-facade.d.ts'];

export interface ScaffoldResult {
	/** The jobs directory that was ensured. */
	dir: string;
	/** Paths whose on-disk content changed in this call (created or refreshed). */
	changed: string[];
}

/**
 * Import specifier for `jobs-sdk.ts` as seen from a file inside the jobs dir.
 * Same-drive paths become plain relative specifiers; paths that
 * `path.relative` cannot express (a different Windows drive) fall back to an
 * absolute `file://` URL, the only portable form. Characters outside the
 * conservative safe set also use the URL form.
 */
export function sdkRuntimeSpecifier(dir: string, targetPath: string): string {
	const rel = relative(dir, targetPath);
	if (!rel || isAbsolute(rel)) return pathToFileURL(targetPath).href;
	const posix = rel.split(sep).join('/');
	if (/^[\w./@-]+$/.test(posix)) return posix.startsWith('.') ? posix : `./${posix}`;
	return pathToFileURL(targetPath).href;
}

function packageJsonContent(): string {
	const pkg = {
		type: 'module',
		imports: {
			'#jobs-sdk': { types: './_sdk.d.ts', default: './_sdk.runtime.ts' }
		}
	};
	return `${JSON.stringify(pkg, null, '\t')}\n`;
}

export function runtimeContent(specifier: string): string {
	// JSON.stringify quoting (J-2 review round 2, D5): pathToFileURL does NOT
	// percent-encode quotes, so a repo path containing `'` used to produce a
	// broken single-quoted re-export; stringify escapes every character that
	// matters. Exported for the escaping test.
	return [
		'// Generated by the web-lair jobs scaffold - do not edit.',
		'// Re-exports the repository jobs SDK so `#jobs-sdk` resolves for user',
		'// job files loaded outside the SvelteKit build (jobs-line plan §5.5).',
		`export * from ${JSON.stringify(specifier)};`,
		''
	].join('\n');
}

/** Node's official type-stripping tsconfig block plus this repo's anchors. */
function tsconfigContent(): string {
	const typeRoots = join(repoRoot, 'node_modules', '@types').split(sep).join('/');
	const config = {
		compilerOptions: {
			noEmit: true,
			target: 'esnext',
			module: 'nodenext',
			moduleResolution: 'nodenext',
			rewriteRelativeImportExtensions: true,
			erasableSyntaxOnly: true,
			verbatimModuleSyntax: true,
			strict: true,
			skipLibCheck: true,
			lib: ['esnext'],
			types: ['node'],
			typeRoots: [typeRoots]
		},
		include: ['./**/*.ts'],
		// The runtime re-export targets repository sources; keeping it out of
		// the program is what makes the facade the single type surface
		// (`#jobs-sdk` resolves through the `types` condition instead).
		exclude: ['_sdk.runtime.ts']
	};
	return `${JSON.stringify(config, null, '\t')}\n`;
}

async function writeIfChanged(path: string, content: string, changed: string[]): Promise<void> {
	let current: string | null = null;
	try {
		current = await readFile(path, 'utf8');
	} catch {
		// Missing file: the write below creates it.
	}
	if (current === content) return;
	// tmp + rename (J-2 review R09): a concurrent reader - another drain
	// tick, a web save, or the typecheck's tsc reading tsconfig.json - must
	// never observe a torn artifact while this process refreshes it.
	const tmp = `${path}.${process.pid}.tmp`;
	try {
		await writeFile(tmp, content, 'utf8');
		await rename(tmp, path);
	} catch (error) {
		await rm(tmp, { force: true }).catch(() => {});
		throw error;
	}
	changed.push(path);
}

/**
 * Ensure `$DATA_DIR/jobs` exists and holds the four generated artifacts:
 * `package.json` (the `#jobs-sdk` import map), `_sdk.runtime.ts` (runtime
 * re-export), `_sdk.d.ts` (the hand-written facade copied from the repo) and
 * `tsconfig.json` (for `jobs.typecheck`). Safe to call on every tick / save.
 */
export async function ensureJobsScaffold(dataDir: string): Promise<ScaffoldResult> {
	const dir = jobsDir(dataDir);
	await mkdir(dir, { recursive: true });
	const changed: string[] = [];
	const sdkPath = join(repoRoot, ...SDK_MODULE_SEGMENTS);
	const facade = await readFile(join(repoRoot, ...FACADE_MODULE_SEGMENTS), 'utf8');
	await Promise.all([
		writeIfChanged(join(dir, 'package.json'), packageJsonContent(), changed),
		writeIfChanged(
			join(dir, '_sdk.runtime.ts'),
			runtimeContent(sdkRuntimeSpecifier(dir, sdkPath)),
			changed
		),
		writeIfChanged(join(dir, '_sdk.d.ts'), facade, changed),
		writeIfChanged(join(dir, 'tsconfig.json'), tsconfigContent(), changed)
	]);
	changed.sort();
	return { dir, changed };
}
